name: Deploy

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: 🔎 EsLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Lint
        run: npm run lint

  Deployment:
    name: 🚀 Deploy on vps
    runs-on: [self-hosted]
    needs: [lint]
    if: ${{github.ref == 'refs/heads/main' && github.event_name == 'push'}}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: run Docker compose
        run: |
          docker compose build --no-cache
          docker compose up -d
          docker system prune --force